// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2E5XKYFOSC347G_mnN1WnHbprlNptTk',
    appId: '1:683000533472:web:5cbde6c00a57e138e95b85',
    messagingSenderId: '683000533472',
    projectId: 'chat-app-b3e33',
    authDomain: 'chat-app-b3e33.firebaseapp.com',
    storageBucket: 'chat-app-b3e33.appspot.com',
    measurementId: 'G-T430M5RC1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTAvKg15qJ8poDpy43AJBpNuZlo-AgzoU',
    appId: '1:683000533472:android:404e5ba19f370b27e95b85',
    messagingSenderId: '683000533472',
    projectId: 'chat-app-b3e33',
    storageBucket: 'chat-app-b3e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABk9_U197MCDtMsVdkFbdt9-cnvmmaUbg',
    appId: '1:683000533472:ios:7a575c2ed92622f4e95b85',
    messagingSenderId: '683000533472',
    projectId: 'chat-app-b3e33',
    storageBucket: 'chat-app-b3e33.appspot.com',
    iosBundleId: 'com.example.chatAppBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABk9_U197MCDtMsVdkFbdt9-cnvmmaUbg',
    appId: '1:683000533472:ios:7a575c2ed92622f4e95b85',
    messagingSenderId: '683000533472',
    projectId: 'chat-app-b3e33',
    storageBucket: 'chat-app-b3e33.appspot.com',
    iosBundleId: 'com.example.chatAppBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC2E5XKYFOSC347G_mnN1WnHbprlNptTk',
    appId: '1:683000533472:web:a121f1c8f3b15bb2e95b85',
    messagingSenderId: '683000533472',
    projectId: 'chat-app-b3e33',
    authDomain: 'chat-app-b3e33.firebaseapp.com',
    storageBucket: 'chat-app-b3e33.appspot.com',
    measurementId: 'G-68NGFB9P6K',
  );
}
